import { Rubik } from "next/font/google";
import "./globals.css";
import "./theme/customTheme.css";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Time Track Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  );
}
