import { Rubik } from "next/font/google"
import "./globals.css"
import "./theme/customTheme.css"
import { QueryClientProvider } from "@tanstack/react-query"
import { queryClient } from "@/utils/queryclient"

const rubik = Rubik({ subsets: ["latin"] })

export const metadata = {
  title: "Time Track Dashboard",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className} suppressHydrationWarning={true}>
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  )
}
